### ISSUE TITLE
config file for verdeter commands

### ISSUE THREAD

**Issue by slashformotion** [ditrit/verdeter#19]
## Description

**As a** `developper`,

**I want** `to write configuration for my commands`

**so that** `i don't have to write code that is mainly configuration for commands `.

such as
```go
	serverTimeoutKey := "server.timeout"
	cfg.GKey(serverTimeoutKey, verdeter.IsInt, "", "Maximum timeout of the http server in second (default is 15s)")
	cfg.SetDefault(serverTimeoutKey, 15)

	serverHostKey := "server.host"
	cfg.GKey(serverHostKey, verdeter.IsStr, "", "Address to bind (default is 0.0.0.0)")
	cfg.SetDefault(serverHostKey, "0.0.0.0")

	serverPortKey := "server.port"
	cfg.GKey(serverPortKey, verdeter.IsInt, "p", "Port to bind (default is 8000)")
	cfg.SetValidator(serverPortKey, validators.CheckTCPHighPort)
	cfg.SetDefault(serverPortKey, 8000)

	paginationMaxElemPerPage := "server.pagination.page.max"
	cfg.GKey(paginationMaxElemPerPage, verdeter.IsUint, "", "The max number of records returned per page")
	cfg.SetDefault(paginationMaxElemPerPage, 100)

```

## Notes

An exemple of configuration below

```yml
name: badaas
dsc: ... 


keys:
  - database.name:
    local: false
    validator: 
    name: allowedValues
    namedOptions:
      order: asc
    options: ["dev", "prod"]
```
